# NUMPY

NUMPY:
impoting numpy for mathematical operations
dir print all the function in the module numpy

In [2]:
import numpy as np
import pdb #python debugger 
import random
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

NUMPY and LIST

In [4]:
u=np.arange(5)
print(u)
print(type(u))
t=list(range(5))
print(t)
print(type(t))

%timeit u**2
%timeit[t**2 for i in t]

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4]
<class 'list'>
693 ns ± 68.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


UsageError: Line magic function `%timeit[t**2` not found.


## operation by numpy is efficiently done


### working with 2 dimensional array

In [3]:
b=np.array([[1,2,3],[2,3,6]])
b

array([[1, 2, 3],
       [2, 3, 6]])

In [4]:
b.ndim

2

In [5]:
b.shape

(2, 3)

##### len function only provides information about number of element in the first column

In [6]:
len(b)

2

#### WORKING WITH 3 DIMENSIONAL ARRAY:

In [7]:
AYY_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(AYY_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
AYY_3.ndim

3

In [9]:
AYY_3.shape

(2, 2, 3)

In [10]:
len(AYY_3)

2

In [11]:
np.arange(1,10,2)#step size of two

array([1, 3, 5, 7, 9])

In [12]:
print(np.linspace(0,1,100))
%timeit np.linspace(0,1,100)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [13]:
print(np.ones((3,3,3),dtype='float64'))#ones takes three argument
print(np.ones(2,dtype='int64'))
np.ones((2,2))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[1 1]


array([[1., 1.],
       [1., 1.]])

In [14]:
print(np.zeros((3,3,3)))#zeroes matrix takes three argument
print(np.zeros((3,3)))
print(np.zeros(3))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3,2)#identity matrix

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

diagonal matrix

In [17]:
ss=np.diag([1,2,3,4,5])
print(ss)
np.diag(ss)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([1, 2, 3, 4, 5])

##### RANDOM ARRAY :USING RAND FUNCTION

In [7]:
print(random.random.__doc__)

random() -> x in the interval [0, 1).


In [18]:
dir(np.random)

['Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_pickle',
 'absolute_import',
 'beta',
 'binomial',
 'bit_generator',
 'bounded_integers',
 'bytes',
 'chisquare',
 'choice',
 'common',
 'default_rng',
 'dirichlet',
 'division',
 'entropy',
 'exponential',
 'f',
 'gamma',
 'generator',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mt19937',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'pcg64',
 'permutation',
 'philox',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'sfc64',
 'shuffle',
 'standard_c

In [19]:
print(np.random.rand.__doc__)
'''Create an array of the given shape and populate it with
        random samples from a uniform distribution
        over ``[0, 1)`'''


        rand(d0, d1, ..., dn)

        Random values in a given shape.

        .. note::
            This is a convenience function for users porting code from Matlab,
            and wraps `numpy.random.random_sample`. That function takes a
            tuple to specify the size of the output, which is consistent with
            other NumPy functions like `numpy.zeros` and `numpy.ones`.

        Create an array of the given shape and populate it with
        random samples from a uniform distribution
        over ``[0, 1)``.

        Parameters
        ----------
        d0, d1, ..., dn : int, optional
            The dimensions of the returned array, must be non-negative.
            If no argument is given a single Python float is returned.

        Returns
        -------
        out : ndarray, shape ``(d0, d1, ..., dn)``
            Random values.

        See Also
        --------
        random

        Examples
        --------
        >>> np.random.rand(3,2)
        array([[

In [20]:
print(np.random.randn.__doc__)
''' If positive int_like arguments are provided, `randn` generates an array
        of shape ``(d0, d1, ..., dn)``, filled
        with random floats sampled from a univariate "normal" (Gaussian)
        distribution of mean 0 and variance 1.'''


        randn(d0, d1, ..., dn)

        Return a sample (or samples) from the "standard normal" distribution.

        .. note::
            This is a convenience function for users porting code from Matlab,
            and wraps `numpy.random.standard_normal`. That function takes a
            tuple to specify the size of the output, which is consistent with
            other NumPy functions like `numpy.zeros` and `numpy.ones`.

        If positive int_like arguments are provided, `randn` generates an array
        of shape ``(d0, d1, ..., dn)``, filled
        with random floats sampled from a univariate "normal" (Gaussian)
        distribution of mean 0 and variance 1. A single float randomly sampled
        from the distribution is returned if no argument is provided.

        Parameters
        ----------
        d0, d1, ..., dn : int, optional
            The dimensions of the returned array, must be non-negative.
            If no argument is given a single Python float is retu

In [8]:
print(np.random.randint.__doc__)
''' Return random integers from `low` (inclusive) to `high` (exclusive).
Return random integers from the "discrete uniform" distribution of'''


        randint(low, high=None, size=None, dtype='l')

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the specified dtype in the "half-open" interval [`low`, `high`). If
        `high` is None (the default), then results are from [0, `low`).

        .. note::
            New code should use the ``integers`` method of a ``default_rng()``
            instance instead; see `random-quick-start`.

        Parameters
        ----------
        low : int or array-like of ints
            Lowest (signed) integers to be drawn from the distribution (unless
            ``high=None``, in which case this parameter is one above the
            *highest* such integer).
        high : int or array-like of ints, optional
            If provided, one above the largest (signed) integer to be drawn
            from the distribution (see above for behavior if ``high=None``).
            If ar

' Return random integers from `low` (inclusive) to `high` (exclusive).\nReturn random integers from the "discrete uniform" distribution of'

In [21]:
np.random.rand(5,5)

array([[0.81834199, 0.0902881 , 0.60518105, 0.64836875, 0.7836918 ],
       [0.49470915, 0.21512194, 0.15687017, 0.6463865 , 0.90343067],
       [0.93537944, 0.34604375, 0.59809735, 0.69032344, 0.72742288],
       [0.45460512, 0.24914632, 0.77519148, 0.37109409, 0.9123597 ],
       [0.21617504, 0.53891704, 0.01348297, 0.97872952, 0.53549687]])

In [22]:
np.random.randn(5,5)

array([[-1.32964692,  0.52847296,  0.65705477,  1.15410627, -0.73943477],
       [-0.06217062,  2.34457023, -0.1836396 ,  0.10413397, -0.63598134],
       [-0.52149222,  1.55768107,  0.15920523, -0.8409391 , -0.66372172],
       [ 0.58108244, -0.04714533,  0.30184221,  1.41923116, -1.39539963],
       [-1.05739413, -0.21522364, -1.22853178,  0.85396842,  0.13426144]])

In [11]:
np.random.randint(5,size=(5,5))

array([[2, 0, 4, 0, 3],
       [2, 0, 3, 1, 3],
       [4, 0, 3, 2, 1],
       [0, 1, 0, 3, 4],
       [2, 0, 4, 4, 3]])

###### INDEXING AND SLICING:
1. INDEXTING:

In [23]:
A=np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


###### slicing

In [24]:
A[5:]=10
A

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [25]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [26]:
A[5:]=b[::-1]
A

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

##### VIEWING AND COPING


In [27]:
AAA=np.arange(12)
cc=AAA[::2]
np.shares_memory(AAA,cc)#does it efficiently

True

In [28]:
cc[0]=11
print(AAA)#both the array get modified
print(cc)

[11  1  2  3  4  5  6  7  8  9 10 11]
[11  2  4  6  8 10]


In [29]:
c=AAA[::2].copy()#FORCE COPY
np.shares_memory(AAA,c)

False

In [30]:
print(np.random.randint.__doc__)


        randint(low, high=None, size=None, dtype='l')

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the specified dtype in the "half-open" interval [`low`, `high`). If
        `high` is None (the default), then results are from [0, `low`).

        Parameters
        ----------
        low : int or array-like of ints
            Lowest (signed) integers to be drawn from the distribution (unless
            ``high=None``, in which case this parameter is one above the
            *highest* such integer).
        high : int or array-like of ints, optional
            If provided, one above the largest (signed) integer to be drawn
            from the distribution (see above for behavior if ``high=None``).
            If array-like, must contain integer values
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``,

##### FANCING INDEXING/WAYS OF CREATING SUBSET 
creating copies not views

In [31]:
pr=(np.random.randint(0,20,15))
print(pr)
mask=(pr%2==0)
pr[mask]=0
pr


[15 18 13  1  4 19 10 19  8 10 12 13  3 14  3]


array([15,  0, 13,  1,  0, 19,  0, 19,  0,  0,  0, 13,  3,  0,  3])

##### BASIC OPERATION: ADDITION
MULTIPICATION

In [13]:
ARRAY1=np.arange(10)
ARRAY1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
ARRAY1+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
ARRAY1=ARRAY1+1

In [37]:
ARRAY1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
type(ARRAY1)

numpy.ndarray

In [38]:
aRRay=np.arange(1,20,2)

In [39]:
aRRay


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
ARRAY1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
aRRay==ARRAY1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [44]:
print(np.array_equal.__doc__)


    True if two arrays have the same shape and elements, False otherwise.

    Parameters
    ----------
    a1, a2 : array_like
        Input arrays.

    Returns
    -------
    b : bool
        Returns True if the arrays are equal.

    See Also
    --------
    allclose: Returns True if two arrays are element-wise equal within a
              tolerance.
    array_equiv: Returns True if input arrays are shape consistent and all
                 elements equal.

    Examples
    --------
    >>> np.array_equal([1, 2], [1, 2])
    True
    >>> np.array_equal(np.array([1, 2]), np.array([1, 2]))
    True
    >>> np.array_equal([1, 2], [1, 2, 3])
    False
    >>> np.array_equal([1, 2], [1, 4])
    False

    


In [45]:
np.array_equal(ARRAY1,aRRay)

False

In [46]:
np.log(ARRAY1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [47]:
np.exp(ARRAY1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [48]:
np.sin(aRRay)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [49]:
np.cos(aRRay)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026,
        0.0044257 ,  0.90744678, -0.75968791, -0.27516334,  0.98870462])

imporing data

In [50]:
print(np.loadtxt.__doc__)


    Load data from a text file.

    Each row in the text file must have the same number of values.

    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
        The characters or list of characters used to indicate the start of a
        comment. None implies no comments. For backwards compatibility, byte
        strings will be decoded as 'latin1'. The default is '#'.


In [51]:
t=np.loadtxt("populations.txt")

In [52]:
t

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

#### ASSIGNING VARIABLE TO COLUMN:

In [56]:
t[:,1:]

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [57]:
A,B,C,D=t.T

In [58]:
A

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [59]:
t

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [61]:
np.argmax(B)

3

In [63]:
POPULATION=t[:,1:]

In [64]:
POPULATION

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [66]:
POPULATION.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [67]:
POPULATION.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

#### BROADCASTING:

In [68]:
print(np.tile.__doc__)


    Construct an array by repeating A the number of times given by reps.

    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.

    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.

    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).

    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.

    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A` along each axis.

    Returns
    -------
    c : ndarray
        The ti

In [69]:
c = np.array([1,2,3,4])

In [70]:
c

array([1, 2, 3, 4])

In [78]:
c=np.tile(c,(4,1))

In [79]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [80]:
b=np.arange(4)

In [81]:
b

array([0, 1, 2, 3])

In [82]:
c+b

array([[1, 3, 5, 7],
       [1, 3, 5, 7],
       [1, 3, 5, 7],
       [1, 3, 5, 7]])

In [19]:
e=np.arange(10,40,10)
print(e.shape)

(3,)


In [20]:
e

array([10, 20, 30])

In [22]:
#creating new axis to the existing array
e=e[:,np.newaxis]
e.shape

(3, 1)

In [23]:
e

array([[10],
       [20],
       [30]])

In [24]:
f=np.array([2,3,1])
f

array([2, 3, 1])

In [25]:
f.shape

(3,)

In [27]:
y=e+f
y

array([[12, 13, 11],
       [22, 23, 21],
       [32, 33, 31]])

        FLATNING AND RESHAPING:raval() and reshaping()

In [28]:
e


array([[10],
       [20],
       [30]])

In [29]:
e.ravel()

array([10, 20, 30])

In [30]:
f

array([2, 3, 1])

In [31]:
f.ravel()

array([2, 3, 1])

In [32]:
c

NameError: name 'c' is not defined

In [102]:
c.ravel()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [103]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [104]:
c=c.ravel()

In [105]:
c

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [107]:
print(np.ravel.__doc__)

Return a contiguous flattened array.

    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.

    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)

    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional

        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
        slowest. Note that the 'C' and 'F' options take no account of
        the memory

In [108]:
print(np.reshape.__doc__)


    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        changing fastest, and the last index changing slowest. Note that
        the 'C

In [109]:
c

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [111]:
np.reshape(c,(4,4))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [123]:
w=np.arange(4*3*2).reshape(4,3,2)
w

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [124]:
w[1,1,1]

9

RESIZE:

In [125]:
WW=np.arange(10)
WW.resize(23)
WW

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [126]:
rr=WW
rr.resize(25)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

#### SORTING DATA:

In [134]:
y

array([[12, 13, 11],
       [22, 23, 21],
       [32, 33, 31]])

In [136]:
y.sort(axis=1)
y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [132]:
print(np.sort.__doc__)


    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.

    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
    

##### FANCING INDEXING:

In [137]:
AEE=np.array([7,9,5,8])

In [138]:
AEE.argsort()

array([2, 0, 3, 1])

end

In [26]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
b=a.T.reshape(3,2)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.shares_memory(a,b)

False

In [29]:
b[0]=50
np.shares_memory(a,b)

False

In [30]:
a


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
yy=np.arange(10)
yy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
random.shuffle(yy)

In [7]:
yy

array([8, 9, 1, 6, 0, 2, 5, 7, 3, 4])